### ISSUE TITLE
CLI not work behind proxy

### ISSUE THREAD

**Issue by acesyde** [Stamplay/stamplay-cli#1]
Hi,

I can't use stamplay-cli behind a proxy at my work.

npm is configured and worked
bower is configured and worked

OS : Windows 7

Thanks a lot

**Comment by mirkods** [comment]
Hi,
i'm not able to reproduce this error because i need more details.
What kind of proxy are you using?
Which is its configuration?
Which version of nodejs?
Can you post a screenshot about the error?

**Comment by acesyde** [comment]
Hi,

![image](https://cloud.githubusercontent.com/assets/958435/12615038/9b3600e2-c503-11e5-95ab-f6da2131cf9a.png)

Proxy : Squid
Type : HTTP / HTTPS

**Comment by mirkods** [comment]
I need more info about the proxy configuration as for example if you have blackelisted addresses or protocol limitations

**Comment by acesyde** [comment]
Protocol limitations (unauthorized) :
- FTP

Blackedlisted :
I don't know 

![image](https://cloud.githubusercontent.com/assets/958435/12615286/1a29a54c-c505-11e5-98a5-9189fbfa490a.png)

**Comment by mirkods** [comment]
It's so strange that you are able to ping the server from the browser but not through the cli.
Can you try to run this nodejs script on your client replacing the appId and apiKey placeholders?

``` javascript
var https = require('https')

var appId = 'YOUR APPID'
var apiKey = 'YOUR APIKEY'

var options = { 
    method: 'GET',
  port: '443',
  host: 'cli.stamplayapp.com',
  path: '/credentials',
  headers: { 
    authorization: 'Basic ' + new Buffer(appId + ':' + apiKey).toString('base64') 
  } 
}

var req = https.request(options, function(res){
  var data = '';
  res.on('data', function(chunk){
    data += chunk;
  })

  res.on('error', function(err){
    console.log('ERROR DURING THE TEST: ', err.message)
  })

  res.on('end', function(){
    if (res.statusCode == 200){
      console.log('TEST OK')
    } else {
      console.log('TEST FAILED : ' + data.toString())
    }
  })
});
req.end();
```

which is the output?

**Comment by acesyde** [comment]
Hi,

Not working with https module
![image](https://cloud.githubusercontent.com/assets/958435/12616490/c482af56-c50b-11e5-95a2-d7fe4c02883b.png)

If i use request module
`var request = require('request');`

```
request('https://cli.stamplayapp.com/credentials', 
    {
        'proxy' : 'http://enterpriseproxyurl:3128',
        'headers' : {
            authorization : 'Basic ' + new Buffer(appId + ':' + apiKey).toString('base64') 
        }
    }
, function(err, res, body) {
  console.log("Got body: ", body);
});
```

![image](https://cloud.githubusercontent.com/assets/958435/12616564/22fed8e8-c50c-11e5-9653-6726e26eed3c.png)

**Comment by mirkods** [comment]
Which version of nodejs are you using?

**Comment by acesyde** [comment]
NodeJS 5.3.0
Npm 3.3.12

**Comment by mirkods** [comment]
With the request module but without the option proxy it works?

**Comment by acesyde** [comment]
Nop request module without proxy parameter not work

**Comment by mirkods** [comment]
Ok perfect I gonna fix it soon, thanks for the debugging

**Comment by acesyde** [comment]
Thanks for the fast feedback ;)

**Comment by mirkods** [comment]
I just added the new feature on development branch, please can you test it?

To test the development version you need to follow this steps:
- clone this repo on a folder and checkout on development branch
- run `npm install`
- go in your stamplay project folder and add in the stamplay.json file this entry `proxy:"http://yourproxyaddress:3128'"`
- now use the bin file that you cloned before to run all the commands, so if you want to run `stamplay start` you must run from your stamplay project folder a command like this `../yourClonedFolder/bin/stamplay start`

Hope that all work well

**Comment by acesyde** [comment]
Thks a lot i'm going to test it next week, i reply in this post after.

**Comment by acesyde** [comment]
It works \o/ thanks a lot

**Comment by mirkods** [comment]
Ok perfect, thanks to you for testing.
I am going to release a new version on npm

**Comment by mirkods** [comment]
Version 1.3.5 has been released :tada:
