### ISSUE TITLE
Cache-Control is not working for uploaded images file on Stamplay...

### ISSUE THREAD

**Issue by hughred22** [Stamplay/stamplay-cli#2]
I can not get the Cache-Control working for user uploaded images on Stamplay... 

So here is my stamplay.json file: 

```
      {
            "appId": "actorreels",
            "apiKey": "*************",
            "public": "./dist/",
            "ignore": [
              "stamplay.json",
              "**/.*",
              "**/node_modules/**"
            ],
            "headers": [
                  {
                    "source" : "**/assets/images/shotgun_static/*.@(jpg|jpeg|gif|png)",
                    "headers" : [
                      {
                        "key" : "Cache-Control",
                        "value" : "max-age=7200"
                      }
                    ]
                  },
                  {
                    "source" : "https://actorreels.stamplayapp.com/upload/cobject/pictures/*.@(jpg|jpeg|gif|png)",
                        "headers" : [
                        {
                            "key" : "Cache-Control",
                            "value" : "max-age=7200"
                        }
                     ]

                  },
                  {
                    "source" : "**/upload/cobject/originalphoto/*.@(jpg|jpeg|gif|png)",
                        "headers" : [
                        {
                            "key" : "Cache-Control",
                            "value" : "max-age=7200"
                        }
                     ]

                  },
                  {
                    "source" : "404.html",
                    "headers" : [
                      {
                        "key" : "Expires",
                        "value" : "1y"
                      }
                    ]
                  }
             ]
          }
```

For the first one directly upload assets using stmaplay deploy, the cache control work. BUT for the seond and thrid items, the pictures and originalphoto are uploaded to stamplay using file upload API. It return the url: https://actorreels.stamplayapp.com/upload/cobject/pictures/[filename].jpg
I want to cache all of those images as well - and those are the big images smashing my site speed now. Here is the demo URL: https://demoreel.com/bellamy-young

As you see https://demoreel.com/assets/images/shotgun_static/demoreel_logo.png has cache control enable. But any other images, for example, https://actorreels.stamplayapp.com/upload/cobject/pictures/1460396325934_570470f1283e037404625445.jpg does not. 

So how can I match those user uploaded images using Stamplay upload API as well and have them caches? 

Thanks!

**Comment by mirkods** [comment]
Hi,
this is not a command line issue because as you noticed the images uploaded from the command line have the correct headers. This issue regards the upload on platfrom side so you need to report it here https://github.com/Stamplay/stamplay-product-development
