### ISSUE TITLE
Single Page App incorrectly routing URLs

### ISSUE THREAD

**Issue by liebrand** [Stamplay/stamplay-cli#3]
I'm running my app as a single page app, which means I would expect to have total control over the URL. However, it appears there are some specific routing issues that result in a 404 that should not happen IMHO:

First if any part of the pathname has dots in it, it will route to a 404, eg:
https://my-app.stamplayapp.com/foo/bar.baz/somethingelse/

And secondly, at least on the local dev server, if the pathname ends on a slash it also fails, eg:
http://localhost:8080/foo  <-- works
http://localhost:8080/foo/ <-- results in 404

**Comment by claudiopetrini** [comment]
Both routing issues should be fixed on version 1.4.4.
